# Generated by Django 4.0.4 on 2022-05-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=64)),
                ('link_project', models.CharField(max_length=1024)),
                ('users_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.usersappmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersapp.usersappmodel')),
            ],
        ),
    ]
