# Generated by Django 4.0.4 on 2022-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_usersappmodel_delete_usersapp'),
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='users_work',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='users_work',
            field=models.ManyToManyField(to='usersapp.usersappmodel'),
        ),
    ]
