# Generated by Django 4.0.4 on 2022-05-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_usersappmodel_delete_usersapp'),
        ('projectapp', '0002_remove_projectmodel_users_work_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='ToDoModel',
        ),
    ]
